services:
    custom_data_source:
        class: FortheHorde\Perso\PersoGen
        tags:
            - { name: sculpin.data_source }
            
    
    forthehorde.extension.wowhead:
        class: FortheHorde\Twig\Extensions\WowHead
        tags: 
           - { name: twig.extension }
    forthehorde.extension.achievement:
        class: FortheHorde\Twig\Extensions\Achievement
        tags: 
           - { name: twig.extension }
    forthehorde.extension.playerachievement:
        class: FortheHorde\Twig\Extensions\PlayerAchievement
        tags: 
           - { name: twig.extension }
    forthehorde.extension.ilevel:
        class: FortheHorde\Twig\Extensions\ILevel
        tags: 
           - { name: twig.extension }
    forthehorde.extension.trade:
        class: FortheHorde\Twig\Extensions\Trade
        tags: 
           - { name: twig.extension }       
    forthehorde.extension.text:
        class: FortheHorde\Twig\Extensions\Text
        tags: 
           - { name: twig.extension }       
           
           
           
           
           
